### PR TITLE
Team compare

### PR DESCRIPTION
**Pull request by aeronut343**
Team Compare page added after Player Compare page. Changed cards on the bottom to reflect more relevant data to team comparison (vs player comparison). I am having trouble getting the team logos to update, but other than that it should be good for review.

### CODE REVIEW

**Comment by PhilMcDaniel** [comment]
@aeronut343 Great stuff again. Couple thoughts on the content that I'd like your take on...
1. Do you think team level score is an important metric to keep? (I'm kinda 50/50 on it leaning towards it not being that valuable.
2. Do you think we can get a "card" for goal differential included? I think its a pretty valuable team level metric
3. Can we add another decimal to the "Assist Ratio" card? Or turn it to a % with 2 decimals?

To get the team logo to work, we need the relationship between team_logos & team_games to be "both directions" Right now we can't just do that due to a Power BI limitation in my screenshot. One solution is to duplicate the team_logos table and have one connected to player_games and one that is connected to team_games. The other option is to figure out a way to remove the need for the "Teams" table. Right now its only used on "Team Shots vs Goals" page to allow the drill-through functionality to work. I'm not against getting rid of that functionality, but I think I'd like to keep it as a secondary option.
image

**Comment by aeronut343** [comment]
@PhilMcDaniel I have added the duplicate logos table and got the functionality to work. I checked the other pages and it looks like everything is intact. I have not come up with a more relevant stat to take the place of "score per game" for the team compare page. I recommend we publish with "score per game" and take feedback from the MNCS server. The changes are pushed to the branch so you can pull them down and take a look. Thoughts?

**Comment by PhilMcDaniel** [comment]
I'm on board with leaving in score/game, was just curious if you had any other ideas. Couple clean up items

1. Can we remove the bar that's appearing in the team logos on the team compare page? "Show bar" = off should take care of it.
image
2. Can we increase the text size in the Team Name slicers? There is some empty space there that we could fill up with larger text. We currently are using Text Size = 16 on Player Compare.
3. Somehow the Player Stats Table, League & Season filters got changed to single select only. This can happen when slicers are synced across tables. Can you change back to multi-select? You might have to un-sync the slicers to make this work appropriately. 
image
4. Looks like some inconsistent header names in the Time Spent by Speed visuals. I like the names on the left side. 
image
5. It looks like something isn't quite right with the min/max values in the gauges... I'm not exactly sure what it is, but within a league + season combination, one of the teams should have the min & max value on the gauge. Might just be using the min/max from the wrong "aggregate table"...? Its also possible that I messed up the DAX code to create those tables.
6. Can you reset the sorting on page 1 to be: Match wins, Game Win %, Goal Difference? Its either shift+click or control+click that lets you sort on multiple columns.  Make sure this is the last thing you do before saving+committing  as the last state you save is what gets defaulted when publishing.

**Comment by PhilMcDaniel** [comment]
Looks good. Closing this out. Will publish after Tero gets back to me

**Pull request merged**
